try {
  throw 0;
} catch (e) {
  let e = new TypeError('explain');
}
