try {
  throw 0;
} catch {
  let e = new TypeError('explain');
}
